In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

age  gender   review education purchased
13   57  Female  Average    School        No
49   25  Female     Good        UG        No
0    30  Female  Average    School        No
16   59    Male     Poor        UG       Yes
47   38  Female     Good        PG       Yes

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test,y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1],test_size=0.2)

In [13]:
X_train

review education
17     Poor        UG
4   Average        UG
8   Average        UG
6      Good    School
38     Good    School
14     Poor        PG
18     Good    School
1      Poor        UG
26     Poor        PG
5   Average    School
43     Poor        PG
41     Good        PG
30  Average        UG
39     Poor        PG
11     Good        UG
7      Poor    School
10     Good        UG
49     Good        UG
45     Poor        PG
12     Poor    School
21  Average        PG
42     Good        PG
35     Poor    School
28     Poor    School
29  Average        UG
34  Average    School
20  Average    School
48     Good        UG
0   Average    School
46     Poor        PG
22     Poor        PG
47     Good        PG
27     Poor        PG
32  Average        UG
40     Good    School
3      Good        PG
15     Poor        UG
33     Good        PG
24  Average        PG
13  Average    School

In [14]:
y_train

17    Yes
4      No
8      No
6      No
38     No
14    Yes
18     No
1      No
26     No
5     Yes
43     No
41    Yes
30     No
39     No
11    Yes
7     Yes
10    Yes
49     No
45    Yes
12     No
21     No
42    Yes
35    Yes
28     No
29    Yes
34     No
20    Yes
48    Yes
0      No
46     No
22    Yes
47    Yes
27     No
32    Yes
40     No
3      No
15     No
33    Yes
24    Yes
13     No
Name: purchased, dtype: object

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [16]:
X_train

review education
17     Poor        UG
4   Average        UG
8   Average        UG
6      Good    School
38     Good    School
14     Poor        PG
18     Good    School
1      Poor        UG
26     Poor        PG
5   Average    School
43     Poor        PG
41     Good        PG
30  Average        UG
39     Poor        PG
11     Good        UG
7      Poor    School
10     Good        UG
49     Good        UG
45     Poor        PG
12     Poor    School
21  Average        PG
42     Good        PG
35     Poor    School
28     Poor    School
29  Average        UG
34  Average    School
20  Average    School
48     Good        UG
0   Average    School
46     Poor        PG
22     Poor        PG
47     Good        PG
27     Poor        PG
32  Average        UG
40     Good    School
3      Good        PG
15     Poor        UG
33     Good        PG
24  Average        PG
13  Average    School

In [17]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [18]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [20]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [21]:
X_train

array([[0., 1.],
       [1., 1.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [1., 2.],
       [1., 0.]])

In [22]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
X_train

array([[1., 2.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.]])

In [23]:
from sklearn.preprocessing import LabelEncoder

In [24]:
le = LabelEncoder()

In [25]:
le.fit(y_train)

LabelEncoder()

In [26]:
y_train

17    Yes
4      No
8      No
6      No
38     No
14    Yes
18     No
1      No
26     No
5     Yes
43     No
41    Yes
30     No
39     No
11    Yes
7     Yes
10    Yes
49     No
45    Yes
12     No
21     No
42    Yes
35    Yes
28     No
29    Yes
34     No
20    Yes
48    Yes
0      No
46     No
22    Yes
47    Yes
27     No
32    Yes
40     No
3      No
15     No
33    Yes
24    Yes
13     No
Name: purchased, dtype: object

In [27]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [28]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [29]:
y_train

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0])